language: node_js
node_js:
  - "12"
cache:
  directories:
    - "node_modules"

jobs:
  include:
    - stage: stage-testing
      script: echo "Testing stage"
    - stage: deploy
      before_script:
        - npm install -g serverless
      script: serverless deploy
      if: branch = master
