language: node_js
node_js:
  - "12"
cache:
  directories:
    - "node_modules"

stages:
  - test
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: test
      script: yarn test
    - stage: deploy
      before_script:
        - npm install -g serverless
      script: skip
      deploy:
        - provider: script
          script: serverless deploy