language: node_js
node_js:
  - "12"
cache:
  directories:
    - "node_modules"

jobs:
  include:
    - stage: deploy
      before_script:
        - npm install -g serverless
      script: skip
      deploy:
        - provider: script
          script: serverless deploy
          on:
            branch: master
