service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10

package:
  exclude:
    - .git/**

functions:
  hello:
    handler: handler.telegramWebhookHandler
    environment:
      MONGODB_DB_NAME: default
      MONGODB_COLLECTION_NAME: netflixBotChats
    events:
      - http:
          method: post
          path: handleevent
  reminder:
    handler: reminder.reminder
    events:
        - schedule:
            rate: rate(1 minute)