service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    DOCUMENT_STORAGE_DB_NAME: default
    DOCUMENT_STORAGE_COLLECTION_NAME: netflixBotChats
    DOCUMENT_STORAGE_CONNECTION_STRING: ${ssm:netflixBotdocumentStorageConnectionString}

package:
  exclude:
    - .git/**

functions:
  hello:
    handler: handler.telegramWebhookHandler
    events:
      - http:
          method: post
          path: handleevent
  reminder:
    handler: reminder.reminder