service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  logs:
    restApi: true
  environment:
    DOCUMENT_STORAGE_DB_NAME: default
    DOCUMENT_STORAGE_COLLECTION_NAME: netflixBotChats
    DOCUMENT_STORAGE_CONNECTION_STRING: ${ssm:/netflixBot/netflixBotdocumentStorageConnectionString}
    TELEGRAM_BOT_TOKEN: ${ssm:/netflixBot/telegramBotToken}
    DEFAULT_NUMBER_OF_PEOPLE: 3
    PAYMENT_IN_EURO: 11.99

package:
  exclude:
    - .git/**

functions:
  hello:
    handler: handler.telegramWebhookHandler
    events:
      - http:
          method: post
          path: handleevent
  reminder:
    handler: reminder.reminder